### ISSUE TITLE
Question about a UserWarning running train_search.py

### ISSUE THREAD

**Issue by christofer-f** [xiaomi-automl/FairDARTS#2]
Hi! 
I am running the command from the README file:
train_search.py --aux_loss_weight 10 --learning_rate 0.005 --batch_size 32 --parse_method threshold_sparse --save 'EXP-lr_0005_alw_10'

I am running on pytorch version: 1.3.1 and I am getting this error:

separate_loss.py:16: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([28, 7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.

I also wonder if it is possible to run the code on mnist dataset by changing cifar to mnist.

I btw really like this code. 

//Christofer

**Comment by tianbaochou** [comment]
> Hi!
> I am running the command from the README file:
> train_search.py --aux_loss_weight 10 --learning_rate 0.005 --batch_size 32 --parse_method threshold_sparse --save 'EXP-lr_0005_alw_10'
> 
> I am running on pytorch version: 1.3.1 and I am getting this error:
> 
> separate_loss.py:16: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([28, 7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
> to run the code on mnist dataset by changing cifar to mnist.
> 
> I btw really like this code.
> 
> //Christofer

You can ignore the warnings from the pytorch broadcasting. You support run in mnist dataset, but as we know, the input channel of mnist dataset is 1, so you need change the EVALNetwork input channel from 3 to 1.

**Comment by christofer-f** [comment]
Thanks for the reply. 
I am currently trying to run through the whole pipeline myself using the MNIST dataset to familiarize myself with the project.
